### ISSUE TITLE
Cannot activate Tab section pop-up

### ISSUE THREAD

**Issue by Kristina001** [jenkinsci/uithemes-plugin#2]
Hi, while I'm trying to config a theme I get a pop-up with "Cannot activate Tab section. Failed to find a set of tabs" message. And no possibility to create theme. Is it known issue ?
Jenkins ver. 1.600
Ubuntu 14.1
Plugin 2.1.1

**Comment by denrockit** [comment]
+1
Plugin not work few weeks since ~1.598 Jenkins version.
Jenkins: 1.605
OS: Ubuntu 14.04.1
Plugin: 2.1.1
